language: ruby
cache: bundler
script:
- docker-compose -f travis-docker-compose.yml run web tox
services:
- docker
deploy:
  provider: heroku
  api_key:
    secure: W1ELLLWgSHka9eaRcBJxlrU/iDNOc0ZIc5fNyYa8wxHwki7iKlCpiaarkrKc6EyGGxpYOejlnobSBP7luTxwa6JxsClcO25w7+XXnuDM+WVO+D2/itVMudf6PF2Jootr5uLx/nW5fqnk/c+j3z2jZAKFrmBTO5/UyMGOnj2srbF/AkURqybaPmqJQcZuHyJTDgHdIUkljweYV1aadJd+hRgMPo2+19o5ieGEcsgG88XW43RzcD/7MWarJJ0TeQT9W5bvy1ASfhSZk1DF+7UZvz9TNV0M3iCtlDS1RnDlO8ls1gWn25QI/xZa/+/LMy062MtP53V+KnxSO1R2ebQ+TR+8g25nypQPrhbDZty7ZM/qtNBhHJ1FDBT03MQ7lp7LcvL27BOXcq1IIFdeag+sOJaNV/YyZZSguDR8/ZjTOQ/1551wDdXVz5fUxoneD4RNRclpYUhRClx/ODCXTmDFk/LbPfZIU+CksS4dXU6RS8MdRjA9bv8DJGGUWWVkPH5GS0r+4MtKoN8VRNoZxFacVgXbferTtgv5+TvdzPZgVj4K6xRCWYSqyWnGiUyxpqz+5+6C73P3jmxqnQOx7hoZpjxRBygDv7FRpfFocbJZbiHWMgdYhxT+74VVrntHzKtqOwf2HTezkUtwZ91LTxY/MVMTrTCUZRPW8mmixWg2sf4=
  app: bububulti
  on:
    repo: koljanos/sga-lti
