language: ruby
cache: bundler
script:
- docker-compose -f travis-docker-compose.yml run web tox
services:
- docker
deploy:
  provider: heroku
  api_key:
    secure: Djqef9L5tsXmb4xUPHgMMZX5ziBDUhQgk2OXBQ1wq9C+/U1936IjPogB7cEmpJWYtcwiP9ENx1ZfyGIUI97+XjlvfSTZMQWc8pwIvu0vcgOPna96es8BtF4NvcD84dGt1hNzZIqUDdid3lGrTvF23cYln2HlW83YtfJMW2ALGk0oihRAp/NR1VhOaWLz1/oaOrjl3HlLa2Qb6yYJqpodpYJKtGxAeMP1Ln9c4fH6aytJM1s3kxAdF62khKF0t/QFH9egeJMSeMtXYWTQAxy2w7T2TYYl06peDp647PIrg9PNXwNL+2yRuKa1dZxKft1rnJqqf1kanTL0XJD68ysT/SRT/6MMwXBONN7e8d/AVArB6mlQ5DHExLM+ewGDW/HSGwJqPRkiEHBLvXRaQvpiUsBBk01qe5kKOb0p3p1gMufIh27tD1XtdRgvUYJUIHVBl3AY/kuSOB0RwfeviLmHd0uGmECRqmzapHVpY+LLhaVgpW4YtX5uDPL8tjts0yrLv66PSXSJADS4Zss/kfmCjakrmXALQZhnrAXQNngm7HjMzxvDcInmy2ki8AiV9ZFTSGwDxfJC0a5vVq16TAZGUEp4OmTl/Sn07bf3TCifPOdg8S73NiyKS4TsLMNnJH4hDoxy7ssNQmTVSGmoAUsbBLY3xeA8JawQhIVwlrnfPEk=
  app: inrolti
  on:
    repo: koljanos/sga-lti
