language: ruby
cache: bundler
script:
- docker-compose -f travis-docker-compose.yml run web tox
services:
- docker
deploy:
  provider: heroku
  api_key:
    secure: j0nM4NykMB/nhQLJplt7bggLInTsDEV39BqtuqEzPCKJxbIeRSbxQB5otmXcPxM19YqVuUCfcMHkQhBMTrrtYaJ3ZHBBfvW1HW2YHZrICRMT0I7UCyKJCvuQVilKOsHRV9Kc1EPc5sZ/y3ARBkSIBS2JXf/PV6HR5w9VmkP6k9C0PQhSmcsB+8RUoFKTYNw69ElwDSDonJs8wKlyEPGIVqQwxCFXb8Cqh3KA/YLEGQN3jCnG9hpoldbAFI16WG7JuxTp9XrV4ru9rp2IxcD916jhm7JgVjjQ7u99OFLiFJBC0lfFqwmtAIn1+LTTwyqy8ZmCjb9XwVgSq8DfWo64n52elAa/D32xgXWFE256Hwc/QdRTUIaMMmRsGiq/LMbWkcg1fsPaxFZSZAHutxVmxSXtxjLubWcT6E2sJ8US+Hvc9XCElGZnowpFHHVOE83Pg0z+8U0lFnyripy3cabt3+s3HkIDR+V2Fh78v9zUm3LSLwr2VeDnJjZ9xISwXFZAnylb/KXth73lALkosDpCX7cKuFjLFLFCZ0PqDi9pcb1aHOcM9Qyx/plFiA75kCxDem6kWdkp4lstezNRGTn6y/a/G53DFnf3murHK3zS5CFAAH5MqjOlsXznM1LSVfnoYKTYNUYzQaoy01Zqcwik1WUgwFu4zm6lJeWNkIwHH/Y=
  app: inrolti
  on:
    repo: koljanos/sga-lti
